[tool.poetry]
name = "penn-scraper-packages"
version = "0.1.0"
description = ""
authors = ["rb404 <55969596+rb404@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
